# Generated by Django 4.1.7 on 2023-04-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spots',
            new_name='Spot',
        ),
    ]
