# Generated by Django 4.1.7 on 2023-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_spots_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='suitableFor',
            field=models.CharField(choices=[('skateboard', 'Skateboarding'), ('bmx', 'BMXing'), ('scooter', 'Scooter riding'), ('roller', 'Rollerblading')], default='skateboard', max_length=50),
        ),
    ]
