# Generated by Django 4.1.7 on 2023-04-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_spot_suitablefor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
