# Generated by Django 4.1.7 on 2023-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_spot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='displayName',
            field=models.CharField(default='name', max_length=10),
        ),
    ]
