# Generated by Django 4.1.7 on 2023-06-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_users_displayname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='displayName',
            new_name='displayNamez',
        ),
    ]
