# Generated by Django 4.1.7 on 2023-06-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_displayname_users_displaynamez'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='displayNamez',
            new_name='displayName',
        ),
    ]
