# Generated by Django 4.1.7 on 2023-06-27 21:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='suitableFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('skateboard', 'Skateboarding'), ('bmx', 'BMXing'), ('scooter', 'Scooter riding'), ('roller', 'Rollerblading')], max_length=50),
        ),
    ]
