# Generated by Django 4.1.7 on 2023-07-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_spot_suitablefor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
