# Generated by Django 4.1.7 on 2023-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
