# Generated by Django 4.1.7 on 2023-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_spot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
