# Generated by Django 4.1.7 on 2023-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_spotimage_alter_spot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
