# Generated by Django 4.1.7 on 2023-07-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_spotimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotImage',
        ),
    ]
