# Generated by Django 5.0 on 2023-12-27 15:18

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_remove_spot_suitablefor'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='suitableFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('skateboard', 'Skateboarding'), ('bmx', 'BMXing'), ('scooter', 'Scooter riding'), ('roller', 'Rollerblading')], default='skateboard', max_length=50),
            preserve_default=False,
        ),
    ]
