# Generated by Django 5.0 on 2023-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_spot_suitablefor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='suitableFor',
        ),
        migrations.AddField(
            model_name='spot',
            name='suitableFor',
            field=models.ManyToManyField(to='database.sportchoices'),
        ),
    ]
