# Generated by Django 5.0 on 2023-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_sportchoices_remove_spot_suitablefor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='suitableFor',
            field=models.ManyToManyField(blank=True, to='database.sportchoices'),
        ),
    ]
