# Generated by Django 5.0 on 2023-12-27 16:44

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_spot_suitablefor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='suitableFor',
        ),
        migrations.DeleteModel(
            name='SportChoices',
        ),
        migrations.AddField(
            model_name='spot',
            name='suitableFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('skateboard', 'Skateboarding'), ('bmx', 'BMXing'), ('scooter', 'Scooter riding'), ('roller', 'Rollerblading')], default='skateboard', max_length=50),
        ),
    ]
