# Generated by Django 5.0 on 2023-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_remove_spot_suitablefor_delete_sportchoices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='suitableFor',
        ),
        migrations.AddField(
            model_name='spot',
            name='suitableFor',
            field=models.ManyToManyField(blank=True, to='database.sportchoices'),
        ),
    ]
