# Generated by Django 5.0 on 2023-12-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_sportchoices_delete_sportchoice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportChoices',
            new_name='SportChoice',
        ),
    ]
