# Generated by Django 5.0 on 2023-12-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_rename_sportchoices_sportchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportchoice',
            old_name='SportChoice',
            new_name='Sport',
        ),
    ]
